### ISSUE TITLE
Optionally fix the graph scaling when redoing the computations.

### ISSUE THREAD

**Issue by lktsui** [lktsui/carbon_xs_gui#13]
Feature request received:

> Would it be possible for you add a checkbox on the main page that would prevent the graph from rescaling the axis when a new calculation is done?  That way you could just change parameters like Pr and Pt and hit the calculator button to see how it changes the profile and fit.

**Comment by edward651** [comment]
This would be awesome!!!  Thanks so much for doing this.  Owe you big time!

Ed.

**Comment by lktsui** [comment]
Feature added in commits 42e23a03f70d966870062cab50ec29579c769b1c and 94992c9324f3160df7f88e26444c9fa3d80b737f

Will be in the next release.

**Comment by lktsui** [comment]
Feature added in commits 42e23a03f70d966870062cab50ec29579c769b1c and 94992c9324f3160df7f88e26444c9fa3d80b737f

Will be in the next release.
