### ISSUE TITLE
Does not render properly on my monitor

### ISSUE THREAD

**Issue by schro-cat** [lktsui/carbon_xs_gui#27]
The program does not render properly on my Microsoft Surface Pro 4. The native resolution is 2736x1824. It has worked properly on my other laptop and desktops. I have tried adjusting the display settings (text size and general app sizing), but none of them appear to affect the size of the text in the GUI.
![will not render](https://cloud.githubusercontent.com/assets/24922861/25075260/b0b9c3d0-22cd-11e7-849b-d15dc931ae4b.PNG)

**Comment by lktsui** [comment]
Support for scaling on high DPI screens has been added in version 1.3.0.
